# The Docker image that will be used to build your app
image: node:lts

pages:
  stage: deploy
  environment: production
  script:
    - touch public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH