project:
  type: book
  output-dir: docs
  execute-dir: project

metadata-files:
  - _book.yml
  - _format.yml

execute:
  freeze: true

filters:
  - section-bibliographies

bibliography: references.bib
reference-section-title: References
citeproc: true

crossref:
  custom:
    - kind: float
      reference-prefix: Flowchart
      key: flw
      latex-env: flowchart

csl: https://www.zotero.org/styles/ecology-letters
