project:
  type: book
  output-dir: public

book:
  title: "Fundamentals of Biodiversity Data Science"
  author:
    - name: "Timothée Poisot"
      orcid: 0000-0002-0735-5184
      email: timothee.poisot@umontreal.ca
      affiliations:
        - name: Université de Montréal
          department: Sciences Biologiques
          city: Montréal
          region: QC
          country: Canada
  date: "8/5/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/kmeans.qmd
    - chapters/gradientdescent.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
  pdf:
    documentclass: scrbook
    toc: true
    toc-depth: 2



