project:
  type: book
  output-dir: docs
  execute-dir: project

execute: 
  freeze: auto

book:
  title: "Data Science for Biodiversity Scientists"
  subtitle: "An introduction to concepts and practices"
  page-navigation: false
  back-to-top-navigation: true
  page-footer: "This work is licensed under the [CC BY-NC 4.0 International License](https://creativecommons.org/licenses/by-nc/4.0/)" 
  language: en-CA
  license: cc-by-nc
  search:
    location: sidebar
    type: overlay
    collapse-after: 1
    limit: 10
    copy-button: true
  sidebar:
    style: floating
    border: false
  downloads: [pdf, epub]
  author:
    - name: "Timothée Poisot"
      orcid: 0000-0002-0735-5184
      email: timothee.poisot@umontreal.ca
      affiliations:
        - name: Université de Montréal
          department: Sciences Biologiques
          city: Montréal
          region: QC
          country: Canada
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/clustering.qmd
    - chapters/gradientdescent.qmd
    - chapters/crossvalidation.qmd
    - chapters/leakage.qmd
    - chapters/classification.qmd
    - chapters/variableselection.qmd
    - chapters/learningcurves.qmd
    - chapters/explanations.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/ecology-letters

fig-cap-location: margin
tbl-cap-location: top

preview:
  port: 4200

format:
  html:
    theme: litera
    linestretch: 1.5
    grid:
      sidebar-width: 350px
      body-width: 800px
      margin-width: 350px
      gutter-width: 2rem
  pdf:
    documentclass: scrbook
    linkcolor: SteelBlue4
    fig-pos: 'bt'
    tbl-pos: 'bt'
    toc: true
    toc-depth: 2
    mainfont: TeX Gyre Termes
    mathfont: TeX Gyre Termes
    sansfont: TeX Gyre Heros
    monofont: TeX Gyre Cursor