project:
  type: book
  output-dir: public
  execute-dir: project

execute: 
  freeze: auto
  cache: true

book:
  title: "Data Science for Biodiversity Scientists"
  subtitle: "An introduction to concepts and practices"
  page-navigation: true
  language: en-CA
  license: cc-by
  search:
    location: sidebar
    type: overlay
    limit: 10
    copy-button: true
  sidebar:
    style: floating
  downloads: pdf
  author:
    - name: "Timothée Poisot"
      orcid: 0000-0002-0735-5184
      email: timothee.poisot@umontreal.ca
      affiliations:
        - name: Université de Montréal
          department: Sciences Biologiques
          city: Montréal
          region: QC
          country: Canada
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/kmeans.qmd
    - chapters/gradientdescent.qmd
    - chapters/splits.qmd
    - chapters/leakage.qmd
    - chapters/classification.qmd
    - chapters/variableselection.qmd
    - chapters/learningcurves.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    fig-pos: 'bt'
    tbl-pos: 'bt'
    toc: true
    toc-depth: 3
    mainfont: TeX Gyre Pagella
    mathfont: TeX Gyre Pagella Math
    sansfont: TeX Gyre Heros
    monofont: TeX Gyre Cursor